# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
soma = 0

for n in range(1, 4000001):
    if fibonacci[-1] + fibonacci[-2] == n:
        fibonacci.append(n)

for i in fibonacci:
    if i % 2 == 0:
        soma += i

print(fibonacci)
print(soma)


